# Generated by Django 4.2.17 on 2025-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
